### PR TITLE
Doc updates and examples with sphinx-gallery

### PR DESCRIPTION
**Pull request by cjacoby**
PR for #58, work in progress.

- [x] Framework Examples
    - [x] Keras
    - [x] sklearn-style APIs (This is covered in the .ipynb)
- [x] Update "Simple Example" to include basic `Streamer` functionality
- [x] Fix / fill out the API Reference
- [x] Buffered streamers example
- [x] ZMQ Example
- [x] Update existing .ipynb to current API, or maybe just convert it into a normal example?
- [x] Mux examples
    - [x] Stream from multiple .npy/.npz files, where each file gets a streamer, and you mux them together.

### CODE REVIEW

**Comment by cjacoby** [comment]
@bmcfee - I'm having trouble getting sphinx-gallery to `make html`, with the following error; any experience with this, or ideas?

```
> make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.4.8
loading pickled environment... not yet created
Generating gallery

Exception occurred:
  File "/usr/local/lib/python3.5/site-packages/sphinx_gallery/gen_rst.py", line 533, in clean_modules
    plt.rcdefaults()
NameError: name 'plt' is not defined
The full traceback has been saved in /var/folders/v5/4fmqb4p56vv4p08283vnlfnc0000gn/T/sphinx-err-x9t3knz9.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 1
```

**Comment by bmcfee** [comment]
> any experience with this, or ideas?

Doesn't look familiar, but matplotlib isn't getting imported somewhere.

I have a working conf.py over in [librosa_gallery](https://github.com/librosa/librosa_gallery/blob/master/docs/conf.py) -- maybe you can diff and narrow down to likely culprits?

**Comment by cjacoby** [comment]
OK thanks, I'll check it out

**Comment by bmcfee** [comment]
@cjacoby any luck on getting the gallery build working?

**Comment by cjacoby** [comment]
gah no :cry: I moved to prioritizing getting actual examples done, since
after too many hours on it i wasn't getting anywhere.

**Comment by bmcfee** [comment]
@cjacoby no problem, I was just checking.

Let me know when you're happy with content, and then I'll work out the build issues.

**Comment by bmcfee** [comment]
Heads up on the keras example: does this work with 2.0?

**Comment by cjacoby** [comment]
Good call. I saw the 2.0 post yesterday, but I haven't checked.

**Comment by bmcfee** [comment]
@cjacoby I pulled this down locally and got it to build after some minor tweaks to the docstring header formatting.  Not sure what's going on on your end, but I think everything's in good shape here.

**Comment by cjacoby** [comment]
Whoa cool, thanks.

How does one do tests on these gallery examples? Whats standard practice there?

**Comment by bmcfee** [comment]
> How does one do tests on these gallery examples? Whats standard practice there?

Hrmmm, good question.  I haven't done that in the past, beyond making sure the thing builds.  Since the librosa gallery needs a lot of heavy machinery to generate the figures, CI doc builds are a non-starter anyway.

I just pushed another change that gets the gallery to build on RTD, so maybe we can just use RTD status for this and not worry too much?

**Comment by bmcfee** [comment]
update: RTD gallery build: https://pescador.readthedocs.io/en/docs-1.0_docs_update/auto_examples/index.html

**Comment by cjacoby** [comment]
Awwwww yeaaaaaaaaah 👍 

I'm gonna try to finish my advanced zmq and mux examples tomorrow morning. 

Any thoughts on what should be included in an advanced zmq example? I was thinking some kind of data augmentation or something.

**Comment by bmcfee** [comment]
> Any thoughts on what should be included in an advanced zmq example? I was thinking some kind of data augmentation or something.

Not really.. what's supposed to be "advanced" about the advanced example?  Do we need both, or would that just be confusing?

**Comment by cjacoby** [comment]
You're right. I think a more significant Mux example is significantly more important / interesting / higher priority.

**Comment by cjacoby** [comment]
To be sure, there could always be more examples, but I think this covers all the basic cases I had in mind, and feels like enough for V1 to me.

Appreciate comments / review on "copy" / "tone" / "content", if you care to give them, @bmcfee @ejhumphrey. Otherwise, I'm satisfied to call this done for now.

**Comment by bmcfee** [comment]
@cjacoby I gave it a quick glance, and noticed a few typos, but otherwise it looks great.

Thanks for doing this!

**Comment by cjacoby** [comment]
I feel fine with you just fixing type-os, if it's easier.

**Comment by bmcfee** [comment]
On it.

**Comment by bmcfee** [comment]
Okay, I think this one's good to go.  I also threw some fishes into the gallery, because why not.

**Pull request merged**
