### PR TITLE
documentation updates for 2.0.0

### PR DESCRIPTION
**Pull request by bmcfee**
Intended fixes:

- [x] #104 - Examples for epoch-based training
- [x] #105 - improve clarity on rate parameter
- [x] #106 - Improved example gallery

### CODE REVIEW

**Comment by bmcfee** [comment]
Note: rtd builds are enabled on this PR [here](https://pescador.readthedocs.io/en/doc-examples-2.0/api.html).

**Comment by bmcfee** [comment]
Hrm, the epoch training example doesn't quite work correctly with `max_iter` set.  Opening a new issue on that.

**Comment by bmcfee** [comment]
This PR is ready for CR.

**Comment by cjacoby** [comment]
Good stuff 🥇  LGTM

**Pull request merged**
