### PR TITLE
[RFC] bugfix ShuffledMux with integer weights

### LINKED ISSUE #143: bug with integer-valued weights in *Mux
A minimal (non)-working example

```python
import numpy
import pescador

def yield_0():
    while True:
        yield 0
        
def yield_1():
    while True:
        yield 1
        
stream_0 = pescador.Streamer(yield_0)
stream_1 = pescador.Streamer(yield_1)

weights = np.array([1, 1])

# This passes
mux = pescador.ShuffledMux(
    [stream_0, stream_1], weights=weights.astype('float'))

# This fails
#mux = pescador.ShuffledMux(
#    [stream_0, stream_1], weights=weights)
```

Traceback:
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-22c8073f17b0> in <module>()
    189 
    190     # Multiplex streamers together.
--> 191     mux = pescador.ShuffledMux(streams, weights=stream_weights)
    192     muxes.append(mux)
    193 

~/miniconda3/envs/bvfs/lib/python3.5/site-packages/pescador/mux.py in __init__(self, streamers, weights, random_state)
    884                                 'one positive value')
    885 
--> 886         self.weights /= np.sum(self.weights)
    887 
    888     def _activate(self):

TypeError: No loop matching the specified signature and casting
was found for ufunc true_divide
```

### PR DESCRIPTION
**Pull request by lostanlen**
Fixes #143

I wrote the (failing) test `test_shuffled_mux_integer_weights`. I will write the bugfix once i make sure that this test reproduces issue #143.

### CODE REVIEW

**Comment by bmcfee** [comment]
It looks like tests are failing because of some incompatibility with pytest 5.

**Comment by lostanlen** [comment]
Yes, this is not at all the error trace i expected!

```python
_____________________ ERROR collecting tests/test_utils.py _____________________
../../../env/miniconda3.6/envs/test-environment/lib/python3.6/site-packages/pluggy/hooks.py:289: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../env/miniconda3.6/envs/test-environment/lib/python3.6/site-packages/pluggy/manager.py:87: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../env/miniconda3.6/envs/test-environment/lib/python3.6/site-packages/pluggy/manager.py:81: in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
../../../env/miniconda3.6/envs/test-environment/lib/python3.6/site-packages/_pytest/python.py:225: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
../../../env/miniconda3.6/envs/test-environment/lib/python3.6/site-packages/_pytest/python.py:401: in _genfunctions
    self.ihook.pytest_generate_tests(metafunc=metafunc)
../../../env/miniconda3.6/envs/test-environment/lib/python3.6/site-packages/pluggy/hooks.py:289: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../env/miniconda3.6/envs/test-environment/lib/python3.6/site-packages/pluggy/manager.py:87: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../env/miniconda3.6/envs/test-environment/lib/python3.6/site-packages/pluggy/manager.py:81: in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
../../../env/miniconda3.6/envs/test-environment/lib/python3.6/site-packages/_pytest/python.py:128: in pytest_generate_tests
    metafunc.parametrize(*marker.args, **marker.kwargs)
../../../env/miniconda3.6/envs/test-environment/lib/python3.6/site-packages/_pytest/python.py:993: in parametrize
    function_definition=self.definition,
../../../env/miniconda3.6/envs/test-environment/lib/python3.6/site-packages/_pytest/mark/structures.py:128: in _for_parametrize
    if len(param.values) != len(argnames):
E   TypeError: object of type 'MarkDecorator' has no len()
```

**Comment by lostanlen** [comment]
i rolled back pytest 5.0 to pytest 4.6, but clearly that wasn't enough. i'm going to roll back to 4.0.1, which is the last time we've seen the master branch build successfully.

**Comment by lostanlen** [comment]
Tests are still failing, but now for the right reason :)
Writing the bugfix

**Comment by lostanlen** [comment]
Tests are passing! This is ready for CR

**Pull request merged**
