### PR TITLE
Docs 1.0.0

### PR DESCRIPTION
**Pull request by bmcfee**
And general preparation for the 1.0 release

### CODE REVIEW

**Comment by bmcfee** [comment]
Docs build and all links check out; I think this is good to go and then we can :shipit:

**Comment by cjacoby** [comment]
Looking from my phone, but LGTM.

**Comment by cjacoby** [comment]
One thought: Is it worth being more explicit about the break with the
previous API? This might be enough. Not sure.

**Comment by bmcfee** [comment]
> Is it worth being more explicit about the break with the
> previous API?

Yup, done.  Not sure we have enough of a user-base that it matters that much, but I threw a line in the changelog about it.

**Comment by cjacoby** [comment]
I can think of at least three other people it might effect ;).

Thanks :+1:

**Pull request merged**
