### PR TITLE
tuple generator

### PR DESCRIPTION
**Pull request by bmcfee**
This implements #56 , and provides a tuple generator interface for all streamer objects.

To-do:

- [x] core implementation
- [x] core unit test for streamer
- [x] integration tests for all derived classes
- [x] cyclic tuple support

### CODE REVIEW

**Comment by bmcfee** [comment]
I added cycle support as an optional kwarg to `tuples`.  Maybe this would be better as a separate method, but it seems kinda redundant.  What do yall think?

**Comment by bmcfee** [comment]
I think this one's good to go -- tuple testing is integrated across all subclasses.

**Comment by bmcfee** [comment]
.. getting a strange heisenbug on zmq streamer though.  Possibly timeout related.  @cjacoby @ejhumphrey want to take a look?

**Comment by bmcfee** [comment]
Hrm.  Heisenbug averted?  This might take a more careful look.

For now though, I think ZMQ issues are safely independent of this PR, so it should be ready for review (and merge, I think).

**Comment by bmcfee** [comment]
> Could try to go deeper.

Probably not worth it -- the changes are relatively superficial.

If there's anything to think about, maybe it's whether this is really the interface we want.  I think it is, but I'm open to suggestions.

**Comment by cjacoby** [comment]
I'm okay merging it here, and changing it in the next couple days if one of
us changes our mind.

Right now I'm feeling good about this interface, though.

**Pull request merged**
